#!/bin/bash

source PKGBUILD

if [ -d prepatch ] ;
then
  cd prepatch
  git pull
  cd ..
else
  git clone git://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git ./prepatch
fi

if [ -d prepatch/queue-$_basekernel ] ;
then
  cd prepatch/queue-$_basekernel
  echo "" > ../../prepatch-$_basekernel.patch
  for i in $(cat ./series); 
  do 
     cat $i >> ../../prepatch-$_basekernel.patch; 
  done
else
  echo "There is no patch-set this time"
fi
